# stages:
#   - prepare
#   - build
#   - deploy
#   - publish

# cache:
#   key:
#     files:
#       - pnpm-lock.yaml
#   paths:
#     - .pnpm-store/
#     - node_modules/

# install_dependencies:
#   stage: prepare
#   tags:
#     - node.js
#   script:
#     - npm i pnpm -g
#     - pnpm i
#     - pnpm recursive install
#   only:
#     - main

include:
  - local: 'apps/bodhi-service/.gitlab-ci.yml'
