stages:
  - prepare
  - build
  - deploy
  - publish

cache:
  paths:
    - node_modules/
    - .pnpm-store/

install_dependencies:
  stage: prepare
  tags:
    - node.js
  script:
    - npm i pnpm -g
    - pnpm install
    - pnpm recursive install
  only:
    - main

include:
  - local: 'apps/bodhi-service/.gitlab-ci.yml'
