export enum Provider {
  GOOGLE_GEMINI = 'google-gemini',
  GOOGLE_VERTEX = 'google-vertex',
  GOOGLE_CLAUDE = 'google-claude',
  OPENAI_COMPLETIONS = 'openai-completion',
  OPENAI_ASSISTANTS = 'openai-assistant',
  ANTHROPIC_CLAUDE = 'anthropic-claude',
  ANTHROPIC_BEDROCK = 'anthropic-bedrock',
  ALIYUN_QWEN = 'aliyun-qwen',
  ALIYUN_WANX = 'aliyun-wanx',
  QCLOUD_HUNYUAN = 'qcloud-hunyuan',
  MOONSHOT_KIMI = 'moonshot-kimi',
  DEEPSEEK = 'deepseek',
  GROQ = 'groq',
}
